// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pb/service_file.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpdateConfServiceClient is the client API for UpdateConfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateConfServiceClient interface {
	UpdateConFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error)
}

type updateConfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateConfServiceClient(cc grpc.ClientConnInterface) UpdateConfServiceClient {
	return &updateConfServiceClient{cc}
}

func (c *updateConfServiceClient) UpdateConFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, "/pb.UpdateConfService/UpdateConFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateConfServiceServer is the server API for UpdateConfService service.
// All implementations must embed UnimplementedUpdateConfServiceServer
// for forward compatibility
type UpdateConfServiceServer interface {
	UpdateConFile(context.Context, *FileRequest) (*FileResponse, error)
	mustEmbedUnimplementedUpdateConfServiceServer()
}

// UnimplementedUpdateConfServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUpdateConfServiceServer struct {
}

func (UnimplementedUpdateConfServiceServer) UpdateConFile(context.Context, *FileRequest) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConFile not implemented")
}
func (UnimplementedUpdateConfServiceServer) mustEmbedUnimplementedUpdateConfServiceServer() {}

// UnsafeUpdateConfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateConfServiceServer will
// result in compilation errors.
type UnsafeUpdateConfServiceServer interface {
	mustEmbedUnimplementedUpdateConfServiceServer()
}

func RegisterUpdateConfServiceServer(s grpc.ServiceRegistrar, srv UpdateConfServiceServer) {
	s.RegisterService(&UpdateConfService_ServiceDesc, srv)
}

func _UpdateConfService_UpdateConFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateConfServiceServer).UpdateConFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UpdateConfService/UpdateConFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateConfServiceServer).UpdateConFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateConfService_ServiceDesc is the grpc.ServiceDesc for UpdateConfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateConfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UpdateConfService",
	HandlerType: (*UpdateConfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConFile",
			Handler:    _UpdateConfService_UpdateConFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service_file.proto",
}
